version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logdb
    volumes:
      - mongo_data:/data/db

  logmanagement:
    build: .
    container_name: logmanagement
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=default

volumes:
  mongo_data:
